"""Archive the VEST ShotLog in FileDB and extract per-shot records (#995).

Typical sequence::

    python -m vaft.cli shotlog archive --source "/Volumes/.../1. ShotLog" --filedb /srv/vest.filedb
    python -m vaft.cli shotlog extract --filedb /srv/vest.filedb
    python -m vaft.cli shotlog triggers --filedb /srv/vest.filedb --output diagnostic-trigger-settings.yaml

``extract`` reads the archived workbooks unless ``--source`` names another
folder. The ``pulse_schedule`` products are then built by the corrective
pipeline's ``ingest_external_diagnostics.py --diagnostic shotlog``.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable
import json
from pathlib import Path


def _filedb(root: Path | None):
    from vaft.database.filedb import FileDB

    return FileDB(root) if root is not None else FileDB.from_config()


def _print(document) -> None:
    print(json.dumps(document, ensure_ascii=False, indent=2, default=str))


def _convert(source: Path, overrides: Path | None):
    from vaft.database.shotlog import build_shot_records, convert_directory

    sessions, manifest = convert_directory(source, overrides_path=overrides)
    return sessions, build_shot_records(sessions), manifest


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m vaft.cli shotlog", description=__doc__.splitlines()[0])
    subparsers = parser.add_subparsers(dest="command", required=True)

    archive = subparsers.add_parser("archive", help="copy the monthly workbooks into legacy/shotlog/input")
    archive.add_argument("--source", type=Path, required=True, help="the operators' ShotLog folder")
    archive.add_argument("--filedb", type=Path, help="FileDB root (default: VAFT_FILEDB_DIR)")
    archive.add_argument("--dry-run", action="store_true", help="report what would be copied")

    extract = subparsers.add_parser("extract", help="convert the workbooks and write per-shot records")
    extract.add_argument("--filedb", type=Path, help="FileDB root (default: VAFT_FILEDB_DIR)")
    extract.add_argument("--source", type=Path, help="workbook folder (default: the FileDB archive)")
    extract.add_argument("--overrides", type=Path, help="review overrides YAML")
    extract.add_argument("--dry-run", action="store_true", help="convert and summarise, write nothing")

    triggers = subparsers.add_parser("triggers", help="write the diagnostic trigger-settings table")
    triggers.add_argument("--output", type=Path, required=True)
    triggers.add_argument("--filedb", type=Path, help="FileDB root (default: VAFT_FILEDB_DIR)")
    triggers.add_argument("--source", type=Path,
                          help="convert this workbook folder (default: read the records in FileDB)")
    triggers.add_argument("--overrides", type=Path, help="review overrides YAML")

    args = parser.parse_args(list(argv) if argv is not None else None)

    from vaft.database.shotlog import archive_workbooks, trigger_table, write_extraction
    from vaft.database.shotlog.archive import input_dir
    from vaft.database.shotlog.batch import summarise

    if args.command == "archive":
        summary = archive_workbooks(args.source, _filedb(args.filedb), dry_run=args.dry_run)
        _print({key: (len(value) if isinstance(value, list) else value) for key, value in summary.items()})
        return 0

    filedb = _filedb(args.filedb) if (args.filedb is not None or args.source is None) else None

    if args.command == "triggers":
        import yaml

        from vaft.database.shotlog.archive import load_records

        if args.source is None:
            # The records `extract` wrote: the table then matches the mapping exactly.
            records = load_records(filedb)
        else:
            _, records, _ = _convert(args.source, args.overrides)
        table = trigger_table(records)
        header = (
            "# Effective diagnostic trigger settings by shot, DAQ clock (ms), generated by\n"
            "# `python -m vaft.cli shotlog triggers` from the VEST ShotLog (#995).\n"
        )
        # Field order as soft_x_rays documents it; shots and labels are already sorted.
        args.output.write_text(header + yaml.safe_dump(table, sort_keys=False), encoding="utf-8")
        _print({"shots": len(table["shots"]), "records": len(records), "output": str(args.output)})
        return 0

    source = args.source if args.source is not None else input_dir(filedb)
    sessions, records, manifest = _convert(source, args.overrides)

    summary = {**summarise(manifest), "records": len(records)}
    if not args.dry_run:
        if filedb is None:
            filedb = _filedb(None)
        summary.update(write_extraction(sessions, records, manifest, filedb))
    _print(summary)
    # Validation findings (a duplicated shot on one sheet) are the ShotLog's
    # own content and stay in the manifest; only an unreadable workbook or
    # sheet fails the run.
    failed = [error for error in manifest["errors"] if error.get("stage") != "validation"]
    return 1 if failed else 0


__all__ = ["main"]
