"""Lazy namespace for external fusion-code adapters."""

from importlib import import_module

__all__ = [
    "CodeConfig",
    "CodeInputs",
    "CodeResult",
    "CodeRunner",
    "CHEASEConfig",
    "CHEASEInputs",
    "CHEASEResult",
    "EFITConfig",
    "EFITConstraintConfig",
    "EFIT_FAILURE_CODES",
    "EFITInitializationConfig",
    "EFITInputs",
    "EFITNumericsConfig",
    "EFITProfileConfig",
    "EFITResult",
    "EFITScientificConfig",
    "EFITSliceStatus",
    "EFITValidationConfig",
    "GPECCaseInputs",
    "GPECModuleRun",
    "GPECSuiteConfig",
    "GPECSuiteResult",
    "base",
    "apply_temporal_continuity",
    "chease",
    "collect_efit_outputs",
    "collect_gpec_suite_outputs",
    "efit",
    "efit_parameter_grid",
    "format_gfile_header_for_gpec",
    "find_chease_executable",
    "generate_constraints_ods",
    "generate_kfile",
    "gfile_to_omas",
    "gpec",
    "init_snakemake_logger",
    "prepare_efit_inputs",
    "resolved_efit_configuration",
    "prepare_chease_inputs",
    "prepare_gpec_suite_case",
    "refine_equilibrium",
    "run_efit",
    "validate_efit_slice",
    "run_chease",
    "run_gpec",
    "run_gpec_suite_case",
    "snakemake",
    "tes",
    "TESConfig",
    "TESInputs",
    "TESResult",
    "prepare_tes_inputs",
    "run_tes",
    "collect_tes_outputs",
    "parse_result_scalars",
    "parse_result_coils",
    "scan_tes",
    "KineticEFITConfig",
    "KineticEFITInputs",
    "KineticEFITResult",
    "PressurePoints",
    "build_kinetic_core_profiles",
    "kinetic_pressure_points",
    "inject_pressure_constraint",
    "scale_plasma",
    "prepare_kinetic_efit_inputs",
    "run_kinetic_efit",
    "run_kinetic_chain",
]

_EXPORT_MAP = {
    "CodeConfig": (".base", "CodeConfig"),
    "CodeInputs": (".base", "CodeInputs"),
    "CodeResult": (".base", "CodeResult"),
    "CodeRunner": (".base", "CodeRunner"),
    "CHEASEConfig": (".chease", "CHEASEConfig"),
    "CHEASEInputs": (".chease", "CHEASEInputs"),
    "CHEASEResult": (".chease", "CHEASEResult"),
    "EFITConfig": (".efit", "EFITConfig"),
    "EFITConstraintConfig": (".efit", "EFITConstraintConfig"),
    "EFIT_FAILURE_CODES": (".efit", "EFIT_FAILURE_CODES"),
    "EFITInputs": (".efit", "EFITInputs"),
    "EFITInitializationConfig": (".efit", "EFITInitializationConfig"),
    "EFITNumericsConfig": (".efit", "EFITNumericsConfig"),
    "EFITProfileConfig": (".efit", "EFITProfileConfig"),
    "EFITResult": (".efit", "EFITResult"),
    "EFITScientificConfig": (".efit", "EFITScientificConfig"),
    "EFITSliceStatus": (".efit", "EFITSliceStatus"),
    "EFITValidationConfig": (".efit", "EFITValidationConfig"),
    "GPECCaseInputs": (".gpec", "GPECCaseInputs"),
    "GPECModuleRun": (".gpec", "GPECModuleRun"),
    "GPECSuiteConfig": (".gpec", "GPECSuiteConfig"),
    "GPECSuiteResult": (".gpec", "GPECSuiteResult"),
    "find_chease_executable": (".chease", "find_chease_executable"),
    "apply_temporal_continuity": (".efit", "apply_temporal_continuity"),
    "collect_efit_outputs": (".efit", "collect_efit_outputs"),
    "collect_gpec_suite_outputs": (".gpec", "collect_gpec_suite_outputs"),
    "format_gfile_header_for_gpec": (".gpec", "format_gfile_header_for_gpec"),
    "efit_parameter_grid": (".efit", "efit_parameter_grid"),
    "generate_constraints_ods": (".efit", "generate_constraints_ods"),
    "generate_kfile": (".efit", "generate_kfile"),
    "gfile_to_omas": (".efit", "gfile_to_omas"),
    "init_snakemake_logger": (".snakemake", "init_snakemake_logger"),
    "prepare_chease_inputs": (".chease", "prepare_chease_inputs"),
    "prepare_efit_inputs": (".efit", "prepare_efit_inputs"),
    "resolved_efit_configuration": (".efit", "resolved_efit_configuration"),
    "prepare_gpec_suite_case": (".gpec", "prepare_gpec_suite_case"),
    "refine_equilibrium": (".chease", "refine_equilibrium"),
    "run_efit": (".efit", "run_efit"),
    "validate_efit_slice": (".efit", "validate_efit_slice"),
    "run_chease": (".chease", "run_chease"),
    "run_gpec": (".gpec", "run_gpec"),
    "run_gpec_suite_case": (".gpec", "run_gpec_suite_case"),
    "TESConfig": (".tes", "TESConfig"),
    "TESInputs": (".tes", "TESInputs"),
    "TESResult": (".tes", "TESResult"),
    "prepare_tes_inputs": (".tes", "prepare_tes_inputs"),
    "run_tes": (".tes", "run_tes"),
    "collect_tes_outputs": (".tes", "collect_tes_outputs"),
    "parse_result_scalars": (".tes", "parse_result_scalars"),
    "parse_result_coils": (".tes", "parse_result_coils"),
    "scan_tes": (".tes", "scan_tes"),
    "KineticEFITConfig": (".efit", "KineticEFITConfig"),
    "KineticEFITInputs": (".efit", "KineticEFITInputs"),
    "KineticEFITResult": (".efit", "KineticEFITResult"),
    "PressurePoints": (".efit", "PressurePoints"),
    "build_kinetic_core_profiles": (".efit", "build_kinetic_core_profiles"),
    "kinetic_pressure_points": (".efit", "kinetic_pressure_points"),
    "inject_pressure_constraint": (".efit", "inject_pressure_constraint"),
    "scale_plasma": (".efit", "scale_plasma"),
    "prepare_kinetic_efit_inputs": (".efit", "prepare_kinetic_efit_inputs"),
    "run_kinetic_efit": (".efit", "run_kinetic_efit"),
    "run_kinetic_chain": (".efit", "run_kinetic_chain"),
}


def __getattr__(name: str):
    if name in {
        "base",
        "efit",
        "gpec",
        "chease",
        "snakemake",
        "tes",
    }:
        module = import_module(f".{name}", __name__)
        globals()[name] = module
        return module
    if name not in _EXPORT_MAP:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = _EXPORT_MAP[name]
    module = import_module(module_name, __name__)
    value = getattr(module, attribute)
    globals()[name] = value
    return value


def __dir__():
    return sorted(list(globals().keys()) + __all__)
