"""Reproducible scientific schematics (issue #890).

``vaft.diagram`` explains concepts -- topology, coordinates, workflows --
where :mod:`vaft.plot` shows data and results. The boundary:

``vaft.formula``
    owns the physics: every equation a diagram depends on is a formula
    function, called here rather than restated.
``vaft.diagram``
    owns explanatory geometry: sampling, projection, camera, annotation.
``vaft.plot``
    owns data and numerical results.

Diagrams: ``magnetic_island`` (poloidal, top and 3-D projections of one
island model) and the stability / operational-space charts
``peeling_ballooning`` (schematic), ``s_alpha_ballooning``, ``hugill``, ``hugill_st``,
``troyon`` and ``li_qa`` (Wesson 1989 empirical / Cheng 1987 theoretical); reduced stability
diagnostics (#1635): ``stability_diagnostic_taxonomy`` and ``interchange_criteria``; single-particle motion: ``exb_drift``, ``curvature_drift``,
``magnetization_current`` and ``toroidal_drift``; tearing physics upstream
of the island: ``rational_surface``, ``delta_prime`` and
``tearing_layer_matching``; 3-D perturbation harmonics:
``normal_field_component``, ``complex_harmonic``, ``toroidal_harmonic_phase``,
``harmonic_real_space_projection`` and ``complex_field_superposition``;
the classification ``collision_processes``; geometric approximations:
``geometry_ordering_map``, ``field_line_geometry``, ``mode_number_mapping`` and
``mhd_mode_geometry_map`` (#1574);
asymptotic orderings (#1627): ``timescale_hierarchy``;
tokamak geometry: ``tokamak_torus``, ``flux_surfaces``, ``shaping_family``,
``hfs_lfs_field``, ``safety_factor_winding``, ``flux_coordinates``,
``poloidal_angle_comparison``, ``unwrapped_flux_surface`` and ``field_line_pitch``;
toroidicity and ripple: ``trapped_and_passing_orbits``, ``toroidal_field_ripple``,
``ripple_well_formation`` and ``stochastic_ripple_orbit``; integrated
modeling (#1085): ``knowledge_basis``, ``computational_realization``,
``physical_abstraction``, ``integrated_modeling_space`` and
``integrated_modeling_process``; the VAFT framework (#1090):
``fusion_science_knowledge_lifecycle``, ``vaft_four_pillars``,
``scientific_workflow``, ``interoperability_layers``,
``scientific_provenance_chain``, ``plasma_state_provenance``, ``scientific_infrastructure_principles``,
``machine_agnostic_architecture``, ``experiment_modeling_theory_data_network``,
``integrated_scientific_framework`` (#1698), ``human_ai_interface`` and ``machine_research_archive``; research
infrastructure (#1636, #1638, #1640, #1641, #1643, #1645), fragmented
against integrated pairs plus the research community and ownership:
``scientific_representation``, ``experimental_research_infrastructure``,
``scientific_credibility``, ``research_modality_architecture``,
``fusion_research_ecosystem`` and ``scientific_ownership_architecture``; the VEST data platform
(#1550): ``vest_data_platform`` and ``vest_data_platform_overview``; the software
and external-code ecosystem (#1648): ``software_dependency_ecosystem`` and
``external_code_integration``; the physics-workflow
spine (#1585): ``plasma_parameter_inference``, ``romero_transformer_balance``,
``resistive_zeff_inference``, ``magnetic_efit``, ``kinetic_efit``,
``analytic_mhd_equilibrium``, ``chease_coupling``, ``tokamaker_coupling``,
``dcon_rdcon_stability``, ``gpec_plasma_response``, ``flare_field_line_topology``,
``neo_neoclassical`` and ``tglf_cgyro_local_transport``; plasma parameter
inference (#1601): ``parameter_inference_overview`` and
``parameter_inference_dependency_graph``; the spatial
vocabulary (#1101): ``tokamak_top_view``, ``cocos_orientation``,
``machine_and_equilibrium_geometry``, ``structured_rz_grid``, ``geometry_to_mesh``,
``logical_to_physical_mapping`` and ``physical_to_flux_mapping``; current-profile
and q topology (#1604): ``current_profile_shapes``, ``q_profile_landmarks``,
``q_profile_topologies`` and ``rational_surface_topology``.

A builder returns a :class:`Diagram`, which holds the TikZ source at once
and renders it to SVG -- the canonical artifact -- on first request (inline
in Jupyter through ``_repr_svg_``). Rendering needs ``latex`` and
``dvisvgm``; importing this package and building a diagram do not.

The committed reference SVGs are regenerated and checked with::

    python -m vaft.diagram.build          # render what changed
    python -m vaft.diagram.build --check  # verify, needs no TeX
"""

from importlib import import_module

__all__ = [
    "magnetic_island",
    "peeling_ballooning",
    "s_alpha_ballooning",
    "stability_diagnostic_taxonomy",
    "interchange_criteria",
    "hugill",
    "hugill_st",
    "troyon",
    "li_qa",
    "exb_drift",
    "curvature_drift",
    "magnetization_current",
    "toroidal_drift",
    "rational_surface",
    "delta_prime",
    "tearing_layer_matching",
    "normal_field_component",
    "complex_harmonic",
    "toroidal_harmonic_phase",
    "harmonic_real_space_projection",
    "complex_field_superposition",
    "collision_processes",
    "geometry_ordering_map",
    "field_line_geometry",
    "mode_number_mapping",
    "mhd_mode_geometry_map",
    "timescale_hierarchy",
    "tokamak_torus",
    "flux_surfaces",
    "shaping_family",
    "hfs_lfs_field",
    "safety_factor_winding",
    "flux_coordinates",
    "poloidal_angle_comparison",
    "unwrapped_flux_surface",
    "field_line_pitch",
    "trapped_and_passing_orbits",
    "toroidal_field_ripple",
    "ripple_well_formation",
    "stochastic_ripple_orbit",
    "guiding_center_invariants",
    "canonical_toroidal_momentum",
    "toroidal_symmetry_breaking",
    "sfl_coordinate_grids",
    "sfl_coordinate_taxonomy",
    "sfl_fourier_convergence",
    "clebsch_field_line_label",
    "ballooning_curvature_drive",
    "ballooning_newcomb_test",
    "ballooning_harmonic_envelope",
    "ballooning_workflow",
    "slab_parity",
    "slab_parity_comparison",
    "poloidal_harmonic_coupling",
    "resonant_layer_matching",
    "disruption_timeline",
    "disruption_causal_chain",
    "runaway_generation",
    "disruption_energy_pathways",
    "kink_mode",
    "sawtooth",
    "stochastic_layer",
    "separatrix_lobes",
    "hot_vde_sequence",
    "cold_vde_bifurcation",
    "plasma_wall_halo_current",
    "vde_timescales",
    "grad_shafranov_domain_decomposition",
    "fixed_vs_free_boundary_equilibrium",
    "limiter_and_diverted_topologies",
    "equilibrium_problem_taxonomy",
    "poloidal_flux_source_decomposition",
    "current_to_q_profile",
    "cylindrical_rational_surfaces",
    "cylindrical_mode_morphology",
    "internal_external_kink",
    "plasma_vacuum_wall",
    "cylindrical_tearing_outer",
    "current_profile_shapes",
    "q_profile_landmarks",
    "q_profile_topologies",
    "rational_surface_topology",
    "slab_field_configuration",
    "current_sheet",
    "harris_sheet",
    "x_point",
    "magnetic_reconnection",
    "island_formation",
    "shear_alfven_wave",
    "fast_magnetosonic_wave",
    "mhd_wave_family",
    "plasma_wall_interaction_processes",
    "plasma_wall_interaction_reflection",
    "plasma_wall_interaction_sputtering",
    "plasma_wall_interaction_recycling",
    "plasma_wall_interaction_energy_partition",
    "spectroscopy_ionization_stages",
    "spectroscopy_transitions",
    "spectroscopy_energy_levels",
    "spectroscopy_spectrum",
    "nbi_particle_lifecycle",
    "nbi_neutral_attenuation",
    "iteration_behavior",
    "branch_bifurcation",
    "basin_of_attraction",
    "grid_induced_two_cycle",
    "branch_selection",
    "o_mode_cutoff",
    "x_mode_dispersion",
    "cma_diagram",
    "profile_propagation",
    "wave_dispersion_omega_k",
    "refractive_index_vs_X",
    "refractive_index_vs_Y",
    "neoclassical_collisionality",
    "ntv_collisionality",
    "ntv_precession_regimes",
    "wall_conditioning_baking",
    "wall_conditioning_gdc",
    "wall_conditioning_boronization",
    "wall_conditioning_sequence",
    "field_aligned_basis",
    "flux_tube_patch",
    "magnetic_shear_field_aligned",
    "ballooning_eigenfunction",
    "ballooning_transit_map",
    "ballooning_boundary_conditions",
    "field_aligned_xpoint_limitation",
    "field_line_action_angle",
    "sfl_coordinate_validity",
    "coordinates_vs_cocos",
    "blob_polarization",
    "blob_current_closure",
    "blob_velocity_scaling",
    "blob_regimes",
    "marfe",
    "divertor_heat_footprint",
    "knowledge_basis",
    "computational_realization",
    "physical_abstraction",
    "integrated_modeling_space",
    "integrated_modeling_process",
    "fusion_science_knowledge_lifecycle",
    "vaft_four_pillars",
    "scientific_workflow",
    "interoperability_layers",
    "scientific_provenance_chain",
    "plasma_state_provenance",
    "scientific_infrastructure_principles",
    "machine_agnostic_architecture",
    "experiment_modeling_theory_data_network",
    "integrated_scientific_framework",
    "human_ai_interface",
    "machine_research_archive",
    "scientific_representation",
    "experimental_research_infrastructure",
    "scientific_credibility",
    "research_modality_architecture",
    "fusion_research_ecosystem",
    "scientific_ownership_architecture",
    "vest_data_platform",
    "vest_data_platform_overview",
    "software_dependency_ecosystem",
    "external_code_integration",
    "plasma_parameter_inference",
    "romero_transformer_balance",
    "resistive_zeff_inference",
    "magnetic_efit",
    "kinetic_efit",
    "analytic_mhd_equilibrium",
    "chease_coupling",
    "tokamaker_coupling",
    "dcon_rdcon_stability",
    "gpec_plasma_response",
    "flare_field_line_topology",
    "neo_neoclassical",
    "tglf_cgyro_local_transport",
    "parameter_inference_overview",
    "parameter_inference_dependency_graph",
    "tokamak_top_view",
    "cocos_orientation",
    "machine_and_equilibrium_geometry",
    "structured_rz_grid",
    "geometry_to_mesh",
    "logical_to_physical_mapping",
    "physical_to_flux_mapping",
    "Diagram",
    "DiagramToolchainError",
]

_LOCATIONS = {
    "magnetic_island": "._magnetic_island",
    "peeling_ballooning": "._stability_space",
    "s_alpha_ballooning": "._stability_space",
    "stability_diagnostic_taxonomy": "._reduced_stability",
    "interchange_criteria": "._reduced_stability",
    "hugill": "._stability_space",
    "hugill_st": "._stability_space",
    "troyon": "._stability_space",
    "li_qa": "._li_qa",
    "exb_drift": "._particle_motion",
    "curvature_drift": "._particle_motion",
    "magnetization_current": "._particle_motion",
    "toroidal_drift": "._particle_motion",
    "rational_surface": "._tearing",
    "delta_prime": "._tearing",
    "tearing_layer_matching": "._tearing",
    "normal_field_component": "._harmonic",
    "complex_harmonic": "._harmonic",
    "toroidal_harmonic_phase": "._harmonic",
    "harmonic_real_space_projection": "._harmonic",
    "complex_field_superposition": "._harmonic",
    "collision_processes": "._collision",
    "geometry_ordering_map": "._geometry",
    "field_line_geometry": "._geometry",
    "mode_number_mapping": "._geometry",
    "timescale_hierarchy": "._orderings",
    "mhd_mode_geometry_map": "._mode_geometry",
    "tokamak_torus": "._tokamak_geometry",
    "flux_surfaces": "._tokamak_geometry",
    "shaping_family": "._tokamak_geometry",
    "hfs_lfs_field": "._tokamak_geometry",
    "safety_factor_winding": "._tokamak_geometry",
    "flux_coordinates": "._tokamak_geometry",
    "poloidal_angle_comparison": "._tokamak_geometry",
    "unwrapped_flux_surface": "._tokamak_geometry",
    "field_line_pitch": "._tokamak_geometry",
    "trapped_and_passing_orbits": "._ripple",
    "toroidal_field_ripple": "._ripple",
    "ripple_well_formation": "._ripple",
    "stochastic_ripple_orbit": "._ripple",
    "guiding_center_invariants": "._guiding_center",
    "canonical_toroidal_momentum": "._guiding_center",
    "toroidal_symmetry_breaking": "._guiding_center",
    "sfl_coordinate_grids": "._sfl_coordinates",
    "sfl_coordinate_taxonomy": "._sfl_coordinates",
    "sfl_fourier_convergence": "._sfl_coordinates",
    "clebsch_field_line_label": "._ballooning",
    "ballooning_curvature_drive": "._ballooning",
    "ballooning_newcomb_test": "._ballooning",
    "ballooning_harmonic_envelope": "._ballooning",
    "ballooning_workflow": "._ballooning",
    "slab_parity": "._slab_parity",
    "slab_parity_comparison": "._slab_parity",
    "poloidal_harmonic_coupling": "._slab_parity",
    "resonant_layer_matching": "._slab_parity",
    "disruption_timeline": "._disruption",
    "disruption_causal_chain": "._disruption",
    "runaway_generation": "._disruption",
    "disruption_energy_pathways": "._disruption",
    "kink_mode": "._mhd_mode",
    "sawtooth": "._sawtooth",
    "stochastic_layer": "._magnetic_topology",
    "separatrix_lobes": "._magnetic_topology",
    "hot_vde_sequence": "._vde",
    "cold_vde_bifurcation": "._vde",
    "plasma_wall_halo_current": "._vde",
    "vde_timescales": "._vde",
    "grad_shafranov_domain_decomposition": "._gs_equilibrium",
    "fixed_vs_free_boundary_equilibrium": "._gs_equilibrium",
    "limiter_and_diverted_topologies": "._gs_equilibrium",
    "equilibrium_problem_taxonomy": "._gs_equilibrium",
    "poloidal_flux_source_decomposition": "._gs_equilibrium",
    "current_to_q_profile": "._cylindrical_modes",
    "cylindrical_rational_surfaces": "._cylindrical_modes",
    "cylindrical_mode_morphology": "._cylindrical_modes",
    "internal_external_kink": "._cylindrical_modes",
    "plasma_vacuum_wall": "._cylindrical_modes",
    "cylindrical_tearing_outer": "._cylindrical_modes",
    "current_profile_shapes": "._equilibrium_profiles",
    "q_profile_landmarks": "._equilibrium_profiles",
    "q_profile_topologies": "._equilibrium_profiles",
    "rational_surface_topology": "._equilibrium_profiles",
    "slab_field_configuration": "._field_configurations",
    "current_sheet": "._field_configurations",
    "harris_sheet": "._field_configurations",
    "x_point": "._field_configurations",
    "magnetic_reconnection": "._field_configurations",
    "island_formation": "._field_configurations",
    "shear_alfven_wave": "._mhd_waves",
    "fast_magnetosonic_wave": "._mhd_waves",
    "mhd_wave_family": "._mhd_waves",
    "plasma_wall_interaction_processes": "._pwi",
    "plasma_wall_interaction_reflection": "._pwi",
    "plasma_wall_interaction_sputtering": "._pwi",
    "plasma_wall_interaction_recycling": "._pwi",
    "plasma_wall_interaction_energy_partition": "._pwi",
    "spectroscopy_ionization_stages": "._spectroscopy",
    "spectroscopy_transitions": "._spectroscopy",
    "spectroscopy_energy_levels": "._spectroscopy",
    "spectroscopy_spectrum": "._spectroscopy",
    "nbi_particle_lifecycle": "._nbi",
    "nbi_neutral_attenuation": "._nbi",
    "iteration_behavior": "._iteration_dynamics",
    "branch_bifurcation": "._iteration_dynamics",
    "basin_of_attraction": "._iteration_dynamics",
    "grid_induced_two_cycle": "._iteration_dynamics",
    "branch_selection": "._iteration_dynamics",
    "o_mode_cutoff": "._cold_plasma_waves",
    "x_mode_dispersion": "._cold_plasma_waves",
    "cma_diagram": "._cold_plasma_waves",
    "profile_propagation": "._cold_plasma_waves",
    "wave_dispersion_omega_k": "._cold_plasma_waves",
    "refractive_index_vs_X": "._cold_plasma_waves",
    "refractive_index_vs_Y": "._cold_plasma_waves",
    "neoclassical_collisionality": "._transport_regimes",
    "ntv_collisionality": "._transport_regimes",
    "ntv_precession_regimes": "._transport_regimes",
    "wall_conditioning_baking": "._wall_conditioning",
    "wall_conditioning_gdc": "._wall_conditioning",
    "wall_conditioning_boronization": "._wall_conditioning",
    "wall_conditioning_sequence": "._wall_conditioning",
    "field_aligned_basis": "._field_aligned",
    "flux_tube_patch": "._field_aligned",
    "magnetic_shear_field_aligned": "._field_aligned",
    "ballooning_eigenfunction": "._field_aligned",
    "ballooning_transit_map": "._field_aligned",
    "ballooning_boundary_conditions": "._field_aligned",
    "field_aligned_xpoint_limitation": "._field_aligned",
    "field_line_action_angle": "._sfl_coordinates",
    "sfl_coordinate_validity": "._sfl_coordinates",
    "coordinates_vs_cocos": "._sfl_coordinates",
    "blob_polarization": "._blob",
    "blob_current_closure": "._blob",
    "blob_velocity_scaling": "._blob",
    "blob_regimes": "._blob",
    "marfe": "._marfe",
    "divertor_heat_footprint": "._divertor_footprint",
    "knowledge_basis": "._integrated_modeling",
    "computational_realization": "._integrated_modeling",
    "physical_abstraction": "._integrated_modeling",
    "integrated_modeling_space": "._integrated_modeling",
    "integrated_modeling_process": "._integrated_modeling",
    "fusion_science_knowledge_lifecycle": "._vaft_concepts",
    "vaft_four_pillars": "._vaft_concepts",
    "scientific_workflow": "._vaft_concepts",
    "interoperability_layers": "._vaft_concepts",
    "scientific_provenance_chain": "._vaft_concepts",
    "plasma_state_provenance": "._vaft_concepts",
    "scientific_infrastructure_principles": "._vaft_concepts",
    "machine_agnostic_architecture": "._vaft_concepts",
    "experiment_modeling_theory_data_network": "._vaft_concepts",
    "integrated_scientific_framework": "._vaft_concepts",
    "human_ai_interface": "._vaft_concepts",
    "machine_research_archive": "._vaft_concepts",
    "scientific_representation": "._research_concepts",
    "experimental_research_infrastructure": "._research_concepts",
    "scientific_credibility": "._research_concepts",
    "research_modality_architecture": "._research_concepts",
    "fusion_research_ecosystem": "._research_concepts",
    "scientific_ownership_architecture": "._research_concepts",
    "vest_data_platform": "._platform",
    "vest_data_platform_overview": "._platform",
    "software_dependency_ecosystem": "._ecosystem",
    "external_code_integration": "._ecosystem",
    "plasma_parameter_inference": "._workflow_specs",
    "romero_transformer_balance": "._workflow_specs",
    "resistive_zeff_inference": "._workflow_specs",
    "magnetic_efit": "._workflow_specs",
    "kinetic_efit": "._workflow_specs",
    "analytic_mhd_equilibrium": "._workflow_specs",
    "chease_coupling": "._workflow_specs",
    "tokamaker_coupling": "._workflow_specs",
    "dcon_rdcon_stability": "._workflow_specs",
    "gpec_plasma_response": "._workflow_specs",
    "flare_field_line_topology": "._workflow_specs",
    "neo_neoclassical": "._workflow_specs",
    "tglf_cgyro_local_transport": "._workflow_specs",
    "parameter_inference_overview": "._workflow_specs",
    "parameter_inference_dependency_graph": "._workflow_specs",
    "tokamak_top_view": "._spatial",
    "cocos_orientation": "._spatial",
    "machine_and_equilibrium_geometry": "._spatial",
    "structured_rz_grid": "._spatial",
    "geometry_to_mesh": "._spatial",
    "logical_to_physical_mapping": "._spatial",
    "physical_to_flux_mapping": "._spatial",
    "Diagram": "._render",
    "DiagramToolchainError": "._render",
}


def __getattr__(name: str):
    if name in _LOCATIONS:
        value = getattr(import_module(_LOCATIONS[name], __name__), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(list(globals().keys()) + __all__)
