#!/usr/bin/env python3
"""Build, validate and publish the VAFT documentation site.

The site has two tracks.  The stable track is built from ``main`` and served at
the root of https://vest-tokamak.github.io/vaft/ ; the development track is
built from ``develop`` and served under ``/develop/``.  Both are composed into a
single tree and published as one commit on the ``gh-pages`` branch, which holds
generated output only.

Each track is built from a *source tree of its own branch*, extracted with
``git archive`` into a temporary directory.  That matters more than it looks:
the documentation includes data generated by introspecting the library, so it
is only correct for the exact tree it was generated from.  Nothing here reads
or writes the caller's checkout, and the branch you happen to be standing on
makes no difference to the result.

    python docs/build.py                      # dry run, both tracks, nothing published
    python docs/build.py --publish            # the same, then one commit on gh-pages
    python docs/build.py --regenerate-only    # refresh _data in this checkout, for a local preview

Publishing is all-or-nothing.  If any track fails to generate, build or
validate, or if the composed tree fails its own checks, ``gh-pages`` is left
exactly as it was.

Exit codes: 0 success, 1 build or validation failure, 2 another publish landed
first, 3 a required tool is missing, 4 the request was refused.
"""

from __future__ import annotations

import argparse
import datetime as _datetime
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

EXIT_OK = 0
EXIT_FAILED = 1
EXIT_RACE = 2
EXIT_TOOLCHAIN = 3
EXIT_REFUSED = 4

SITE_URL = "https://vest-tokamak.github.io"
PUBLISH_BRANCH = "gh-pages"
PROVENANCE_SCHEMA = 1
#: Nothing legitimate approaches this; a runaway ``vendor/`` copy does.
MAX_SITE_MIB = 40


class BuildError(RuntimeError):
    """A step failed.  Nothing has been published."""


class ToolchainError(RuntimeError):
    """A required external tool is missing."""


class PublishRace(RuntimeError):
    """The publish branch moved while this build was running."""


@dataclass(frozen=True)
class TrackSpec:
    """The fixed identity of a documentation track."""

    name: str
    default_ref: str
    prefix: str  # "" for the site root, "develop" for the subdirectory
    baseurl: str
    configs: tuple[str, ...]


TRACKS: dict[str, TrackSpec] = {
    "stable": TrackSpec("stable", "origin/main", "", "/vaft", ("_config.yml",)),
    "development": TrackSpec(
        "development",
        "origin/develop",
        "develop",
        "/vaft/develop",
        ("_config.yml", "_config.develop.yml"),
    ),
}


@dataclass
class Track:
    """A track resolved to a specific commit and, later, an extracted tree."""

    spec: TrackSpec
    ref: str
    commit: str
    commit_date: str
    root: Path | None = None
    site: Path | None = None
    vaft_version: str = ""
    pages: int = 0
    outputs: list[str] = field(default_factory=list)

    @property
    def name(self) -> str:
        return self.spec.name

    @property
    def docs(self) -> Path:
        if self.root is None:
            raise BuildError(f"{self.name}: source tree has not been extracted")
        return self.root / "docs"


# --------------------------------------------------------------------------
# small helpers
# --------------------------------------------------------------------------


def _run(
    command: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
    capture: bool = True,
    check: bool = True,
) -> subprocess.CompletedProcess:
    result = subprocess.run(
        command,
        cwd=None if cwd is None else str(cwd),
        env=env,
        capture_output=capture,
        text=True,
    )
    if check and result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        raise BuildError(f"command failed ({result.returncode}): {' '.join(command)}\n{detail}")
    return result


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return _run(["git", *args], cwd=repo, check=check)


def _require(tool: str) -> None:
    if shutil.which(tool) is None:
        raise ToolchainError(f"{tool!r} is not on PATH")


def _now() -> str:
    return _datetime.datetime.now(_datetime.timezone.utc).replace(microsecond=0).isoformat()


def _load_yaml(path: Path):
    try:
        import yaml
    except ModuleNotFoundError as exc:  # pragma: no cover - depends on the environment
        raise ToolchainError(
            "PyYAML is required by docs/build.py; it ships with vaft, so "
            "`pip install -e .` in the repository root, or `pip install pyyaml`"
        ) from exc
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _dump_yaml(data, path: Path) -> None:
    import yaml

    path.write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False),
        encoding="utf-8",
    )


#: ``path``/``sha256`` pairs, in either the block style the formula catalog uses
#: or the flow style the diagnostic registry uses.
_SOURCE_PAIR = re.compile(r"path:\s*([^\s,}\]]+)\s*,?\s*sha256:\s*([0-9a-f]{64})")


def _declared_sources(snapshot: Path) -> list[tuple[str, str]]:
    return _SOURCE_PAIR.findall(snapshot.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------
# resolving and extracting the source trees
# --------------------------------------------------------------------------


def resolve_track(spec: TrackSpec, ref: str, repo: Path) -> Track:
    """Pin a track to one commit, so every later step names the same tree."""
    resolved = _git(repo, "rev-parse", "--verify", f"{ref}^{{commit}}").stdout.strip()
    date = _git(repo, "show", "-s", "--format=%cI", resolved).stdout.strip()
    return Track(spec=spec, ref=ref, commit=resolved, commit_date=date)


def export_source(track: Track, destination: Path, repo: Path) -> Path:
    """Extract the track's commit into ``destination``.

    ``git archive`` rather than ``git worktree``: it registers nothing, takes no
    lock, cannot collide with a branch that is already checked out somewhere
    else, and needs no cleanup beyond removing the directory.
    """
    destination.mkdir(parents=True, exist_ok=True)
    archive = destination.parent / f"{track.name}.tar"
    _git(repo, "archive", "--format=tar", "-o", str(archive), track.commit)
    _run(["tar", "-xf", str(archive), "-C", str(destination)])
    archive.unlink()
    if not (destination / "docs").is_dir():
        raise BuildError(
            f"{track.name}: {track.ref} ({track.commit[:7]}) has no docs/ directory. "
            "Both branches must carry the site source before either can be published."
        )
    track.root = destination
    track.vaft_version = _read_version(destination)
    return destination


def _read_version(root: Path) -> str:
    """Read ``vaft.version.__version__`` as text.

    Parsed rather than imported: this is a second copy of the package, and
    importing it would put the wrong ``vaft`` in this interpreter.
    """
    source = (root / "vaft" / "version.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', source, re.M)
    return match.group(1) if match else "unknown"


# --------------------------------------------------------------------------
# generated data
# --------------------------------------------------------------------------


def declared_generators(docs: Path) -> list[dict]:
    """What this branch says its documentation is generated from."""
    manifest = docs / "generators.yml"
    if not manifest.is_file():
        return []
    return _load_yaml(manifest).get("generators") or []


def regenerate_data(track: Track, *, quiet: bool = False) -> None:
    """Run the generators the track declares, against the track's own tree."""
    generators = declared_generators(track.docs)
    if not generators:
        raise BuildError(f"{track.name}: docs/generators.yml declares no generators")

    env = dict(os.environ)
    env["PYTHONPATH"] = str(track.root)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env.pop("PYTHONHOME", None)

    for generator in generators:
        module, output = generator["module"], generator["output"]
        target = track.docs / output
        target.parent.mkdir(parents=True, exist_ok=True)
        _run(
            [
                sys.executable, "-m", module,
                "--output", str(target),
                "--provenance-commit", track.commit,
                "--provenance-ref", track.ref,
            ],
            cwd=track.root,
            env=env,
        )
        _verify_generated_from_track(track, target, module)
        track.outputs.append(output)
        if not quiet:
            size = target.stat().st_size
            print(f"    {output:<34} {size:>8,} bytes   source verified")


def _verify_generated_from_track(track: Track, snapshot: Path, module: str) -> None:
    """Prove the generator read *this* tree and not another installed copy.

    ``PYTHONPATH`` normally wins, but an editable install can register a
    meta-path finder that does not care about it.  Every snapshot already
    records a checksum of each source file it describes, so re-deriving those
    checksums from the track's tree turns the snapshot into its own receipt.
    """
    pairs = _declared_sources(snapshot)
    if not pairs:
        raise BuildError(f"{track.name}: {snapshot.name} records no source checksums to verify")
    for relative, recorded in pairs:
        source = track.root / relative
        if not source.is_file():
            raise BuildError(f"{track.name}: {snapshot.name} names a missing source {relative}")
        actual = hashlib.sha256(source.read_bytes()).hexdigest()
        if actual != recorded:
            raise BuildError(
                f"{track.name}: {module} ran against a different tree than {track.commit[:7]}. "
                f"{relative} hashes to {actual[:12]} but the snapshot records {recorded[:12]}."
            )


def write_track_provenance(track: Track) -> Path:
    """Record which tree this track was built from, for the page footer."""
    target = track.docs / "_data" / "provenance.yml"
    target.parent.mkdir(parents=True, exist_ok=True)
    _dump_yaml(
        {
            "schema_version": PROVENANCE_SCHEMA,
            "track": track.name,
            "ref": track.ref,
            "commit": track.commit,
            "short_commit": track.commit[:7],
            "commit_date": track.commit_date,
            "vaft_version": track.vaft_version,
            "generated_at": _now(),
        },
        target,
    )
    return target


# --------------------------------------------------------------------------
# building and validating one track
# --------------------------------------------------------------------------


#: The docs/ directory of the checkout running this script.  The Ruby gems are
#: installed against *its* Gemfile -- by `bundle install` locally, by
#: ruby/setup-ruby in CI -- so every bundler command runs from here, with the
#: extracted tree passed in as data.  Running bundler inside the extracted tree
#: instead finds a Gemfile with no gems installed against it.
BUNDLE_ROOT = Path(__file__).resolve().parent


def _bundle_env() -> dict[str, str]:
    env = dict(os.environ)
    env["BUNDLE_GEMFILE"] = str(BUNDLE_ROOT / "Gemfile")
    return env


def build_track(track: Track, destination: Path) -> Path:
    """Render the track with Jekyll at its own baseurl."""
    _require("bundle")
    configs = ",".join(str(track.docs / name) for name in track.spec.configs)
    _run(
        [
            "bundle", "exec", "jekyll", "build",
            "--source", str(track.docs),
            "--config", configs,
            "--baseurl", track.spec.baseurl,
            "--destination", str(destination),
        ],
        cwd=BUNDLE_ROOT,
        env=_bundle_env(),
    )
    track.site = destination
    track.pages = len(list(destination.rglob("*.html")))
    return destination


def validate_track(track: Track) -> None:
    """Run the site's own validator against this track's build and source."""
    _require("ruby")
    env = _bundle_env()
    env["VAFT_DOCS_BASEURL"] = track.spec.baseurl
    env["VAFT_DOCS_SITE"] = str(track.site)
    env["VAFT_NOTEBOOK_SOURCE"] = str(track.root)
    env["VAFT_REGISTRY_SOURCE"] = str(track.root)
    # Through bundler because the validator requires nokogiri, and from the
    # track's own docs/ because the script resolves _data and _guide relative
    # to itself.
    result = _run(
        ["bundle", "exec", "ruby", "scripts/validate_docs.rb"],
        cwd=track.docs, env=env, check=False,
    )
    if result.returncode != 0:
        raise BuildError(
            f"{track.name}: validate_docs.rb failed\n{(result.stderr or result.stdout).strip()}"
        )


# --------------------------------------------------------------------------
# composition
# --------------------------------------------------------------------------


def compose(tracks: list[Track], destination: Path) -> Path:
    """Lay the tracks out as one publishable tree."""
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True)

    for track in tracks:
        target = destination if not track.spec.prefix else destination / track.spec.prefix
        if track.site is None:
            raise BuildError(f"{track.name}: nothing was built")
        shutil.copytree(track.site, target, dirs_exist_ok=True)

    (destination / ".nojekyll").write_text("", encoding="utf-8")
    _dump_yaml(
        {
            "schema_version": PROVENANCE_SCHEMA,
            "generated_at": _now(),
            "generator": "docs/build.py",
            "site": {"url": SITE_URL, "baseurl": "/vaft"},
            "tracks": {
                track.name: {
                    "prefix": "/" + (track.spec.prefix + "/" if track.spec.prefix else ""),
                    "baseurl": track.spec.baseurl,
                    "ref": track.ref,
                    "commit": track.commit,
                    "commit_date": track.commit_date,
                    "vaft_version": track.vaft_version,
                    "pages": track.pages,
                    "generated": track.outputs,
                }
                for track in tracks
            },
        },
        destination / "provenance.yml",
    )
    (destination / "README.md").write_text(
        "# VAFT documentation, published\n\n"
        "This branch is **generated output**. Every file here is written by\n"
        "`docs/build.py` and replaced wholesale on each publish, so an edit made\n"
        "here survives exactly until the next one and reaches nobody's review.\n\n"
        "The source lives in `docs/` on the code branches: the site root is built\n"
        "from `main`, and `/develop/` is built from `develop`. `provenance.yml`\n"
        "records which commit each half came from.\n\n"
        "To change the documentation, change `docs/` on the branch it belongs to.\n",
        encoding="utf-8",
    )
    return destination


def validate_composed(tree: Path, tracks: list[Track]) -> None:
    """Check the properties only the composed tree can have.

    Deliberately in Python and not in ``validate_docs.rb``: that validator is
    per-track and reads ``_data``/``_guide``, none of which exist in output, and
    this has to run under a bare ``pytest -q`` on a machine with no Ruby.
    """
    problems: list[str] = []
    by_name = {track.name: track for track in tracks}

    for track in tracks:
        index = tree / track.spec.prefix / "index.html" if track.spec.prefix else tree / "index.html"
        if not index.is_file():
            problems.append(f"{track.name}: no index.html at {index.relative_to(tree)}")

    for required in (".nojekyll", "provenance.yml"):
        if not (tree / required).is_file():
            problems.append(f"missing {required}")

    if (tree / "provenance.yml").is_file():
        recorded = _load_yaml(tree / "provenance.yml").get("tracks", {})
        for name, track in by_name.items():
            got = (recorded.get(name) or {}).get("commit")
            if got != track.commit:
                problems.append(f"provenance.yml records {name} as {got!r}, built {track.commit!r}")

    # Nothing that is tooling rather than content may reach the published tree.
    for leaked in ("Gemfile", "Gemfile.lock", "package.json", "playwright.config.js",
                   "build.py", "generators.yml", "scripts", "vendor", "tests", "node_modules"):
        for found in tree.rglob(leaked):
            problems.append(f"tooling leaked into the site: {found.relative_to(tree)}")

    develop_prefix = TRACKS["development"].prefix
    for page in tree.rglob("*.html"):
        relative = page.relative_to(tree)
        in_develop = relative.parts and relative.parts[0] == develop_prefix
        text = page.read_text(encoding="utf-8", errors="replace")

        has_noindex = 'name="robots"' in text and "noindex" in text
        if in_develop and not has_noindex:
            problems.append(f"development page without noindex: {relative}")
        if not in_develop and has_noindex:
            problems.append(f"stable page carries noindex: {relative}")

        for reference in re.findall(r'(?:href|src)="(/vaft/[^"#?]*)', text):
            target = tree / reference[len("/vaft/"):]
            if target.is_dir():
                target = target / "index.html"
            if not reference.endswith("/") and not target.exists():
                candidate = Path(str(target) + ".html")
                if candidate.exists():
                    continue
            if not target.exists():
                problems.append(f"{relative}: unresolved link {reference}")
        if not in_develop:
            for reference in re.findall(r'href="(/vaft/develop/[^"]*)"', text):
                problems.append(f"stable page links into the development track: {relative} -> {reference}")

    size_mib = sum(p.stat().st_size for p in tree.rglob("*") if p.is_file()) / 1048576
    if size_mib > MAX_SITE_MIB:
        problems.append(f"composed tree is {size_mib:.1f} MiB, over the {MAX_SITE_MIB} MiB ceiling")

    if problems:
        shown = "\n  ".join(sorted(set(problems))[:40])
        raise BuildError(f"composed site failed validation:\n  {shown}")


# --------------------------------------------------------------------------
# publishing
# --------------------------------------------------------------------------


def remote_tip(repo: Path, remote: str, branch: str) -> str:
    result = _git(repo, "ls-remote", remote, f"refs/heads/{branch}")
    line = result.stdout.strip()
    if not line:
        raise BuildError(f"{remote} has no {branch} branch to publish onto")
    return line.split()[0]


def publish(
    tree: Path,
    repo: Path,
    parent: str,
    message: str,
    *,
    remote: str = "origin",
    branch: str = PUBLISH_BRANCH,
    scratch: Path,
) -> str:
    """Commit the composed tree onto ``branch`` and push it, or fail cleanly.

    Built with plumbing against a throwaway index, so no working tree is
    touched and no destructive git command is ever run.  The new commit's
    parent is the tip read before the build started, which makes the push an
    ordinary fast-forward: if anything else published in the meantime, git
    rejects it and nothing is overwritten.
    """
    scratch.mkdir(parents=True, exist_ok=True)
    git_dir = _git(repo, "rev-parse", "--git-common-dir").stdout.strip()
    git_dir = str((repo / git_dir).resolve()) if not os.path.isabs(git_dir) else git_dir

    env = dict(os.environ)
    env["GIT_INDEX_FILE"] = str(scratch / "publish.index")
    env["GIT_DIR"] = git_dir
    env["GIT_WORK_TREE"] = str(tree)

    _run(["git", "add", "--all", "--force", "."], cwd=tree, env=env)
    tree_sha = _run(["git", "write-tree"], cwd=tree, env=env).stdout.strip()

    message_file = scratch / "commit-message"
    message_file.write_text(message, encoding="utf-8")
    commit_env = {k: v for k, v in env.items() if k != "GIT_WORK_TREE"}
    commit = _run(
        ["git", "commit-tree", tree_sha, "-p", parent, "-F", str(message_file)],
        cwd=repo,
        env=commit_env,
    ).stdout.strip()

    pushed = _run(
        ["git", "push", remote, f"{commit}:refs/heads/{branch}"], cwd=repo, check=False
    )
    if pushed.returncode != 0:
        stderr = (pushed.stderr or "") + (pushed.stdout or "")
        if re.search(r"\b403\b|permission|denied|not authorized|read-only", stderr, re.I):
            raise BuildError(
                f"pushing {branch} was refused for lack of permission:\n{stderr.strip()}\n\n"
                "The publish job asks for `contents: write`.  If the organisation forbids "
                "write-scoped workflow tokens, use the deploy-key fallback in docs/README.md: "
                "add a write-enabled deploy key as a secret and point the remote at SSH before "
                "running with --publish."
            )
        if re.search(r"non-fast-forward|fetch first|rejected", stderr, re.I):
            raise PublishRace(
                f"{branch} moved while this build was running.\n"
                f"  expected tip: {parent}\n"
                f"  remote tip:   {remote_tip(repo, remote, branch)}\n"
                f"  built commit: {commit} (created locally, not pushed)\n"
                "Nothing was published. Re-run docs/build.py --publish."
            )
        raise BuildError(f"pushing {branch} failed:\n{stderr.strip()}")
    return commit


def _commit_message(tracks: list[Track]) -> str:
    by_name = {track.name: track for track in tracks}
    stable, development = by_name["stable"], by_name["development"]
    lines = [
        f"docs: publish site (main {stable.commit[:7]}, develop {development.commit[:7]})",
        "",
        f"stable      {stable.ref:<18} {stable.commit}",
        f"development {development.ref:<18} {development.commit}",
        "",
        "Generated by docs/build.py. This branch is output only; see README.md.",
    ]
    run_url = os.environ.get("GITHUB_RUN_URL")
    if run_url:
        lines.append(f"Run {run_url}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------


def _regenerate_only(repo: Path, quiet: bool) -> int:
    """Refresh this checkout's generated _data, for a local preview."""
    docs = repo / "docs"
    generators = declared_generators(docs)
    if not generators:
        print("docs/generators.yml declares no generators", file=sys.stderr)
        return EXIT_FAILED
    head = _git(repo, "rev-parse", "HEAD").stdout.strip()
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    track = Track(
        spec=TRACKS["development"], ref=branch, commit=head,
        commit_date=_git(repo, "show", "-s", "--format=%cI", head).stdout.strip(),
        root=repo, vaft_version=_read_version(repo),
    )
    if not quiet:
        print(f"==> regenerating docs/_data from {branch} ({head[:7]})")
    regenerate_data(track, quiet=quiet)
    write_track_provenance(track)
    if not quiet:
        print("    _data/provenance.yml")
    return EXIT_OK


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build, validate and publish the VAFT documentation site.",
    )
    parser.add_argument("--stable-ref", default=TRACKS["stable"].default_ref,
                        help="commit-ish for the site root (default: %(default)s)")
    parser.add_argument("--develop-ref", default=TRACKS["development"].default_ref,
                        help="commit-ish for /develop/ (default: %(default)s)")
    parser.add_argument("--track", choices=["both", "stable", "development"], default="both",
                        help="build one track only; cannot be combined with --publish")
    parser.add_argument("--output", type=Path,
                        help="keep the composed tree here instead of a temporary directory")
    parser.add_argument("--publish", action="store_true",
                        help=f"commit and push the composed tree to {PUBLISH_BRANCH}")
    parser.add_argument("--regenerate-only", action="store_true",
                        help="refresh this checkout's docs/_data and exit")
    parser.add_argument("--remote", default="origin")
    parser.add_argument("--branch", default=PUBLISH_BRANCH)
    parser.add_argument("--no-fetch", action="store_true", help="skip `git fetch`")
    parser.add_argument("--keep-temp", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    arguments = parser.parse_args(argv)

    repo = Path(__file__).resolve().parents[1]
    say = (lambda *a: None) if arguments.quiet else print

    try:
        _require("git")
        if arguments.regenerate_only:
            return _regenerate_only(repo, arguments.quiet)

        if arguments.publish and arguments.track != "both":
            print(
                "refusing to publish a single track: the composed tree replaces the whole "
                f"{arguments.branch} branch, so publishing one half would delete the other.",
                file=sys.stderr,
            )
            return EXIT_REFUSED

        if not arguments.no_fetch:
            _git(repo, "fetch", "--no-tags", arguments.remote, "main", "develop", check=False)

        say("==> resolving inputs")
        wanted = ["stable", "development"] if arguments.track == "both" else [arguments.track]
        refs = {"stable": arguments.stable_ref, "development": arguments.develop_ref}
        tracks = [resolve_track(TRACKS[name], refs[name], repo) for name in wanted]
        for track in tracks:
            say(f"    {track.name:<12} {track.ref:<16} {track.commit[:7]}  {track.commit_date}")

        parent = None
        if arguments.publish:
            parent = remote_tip(repo, arguments.remote, arguments.branch)
            say(f"    {arguments.branch} tip {parent[:7]}")

        scratch = Path(tempfile.mkdtemp(prefix="vaft-docs-"))
        try:
            for track in tracks:
                say(f"==> {track.name}: exporting, regenerating, building")
                export_source(track, scratch / "src" / track.name, repo)
                regenerate_data(track, quiet=arguments.quiet)
                write_track_provenance(track)
                build_track(track, scratch / "site" / track.name)
                say(f"    jekyll build{'':<22} {track.pages} pages")
                validate_track(track)
                say(f"    validate_docs.rb{'':<18} passed")

            say("==> composing")
            composed = compose(tracks, scratch / "composed")
            for track in tracks:
                prefix = "/" + (track.spec.prefix + "/" if track.spec.prefix else "")
                say(f"    {prefix:<12} {track.pages} pages from {track.commit[:7]}")

            if arguments.track == "both":
                say("==> validating composed tree")
                validate_composed(composed, tracks)
                say("    links, noindex, tooling and size checks passed")
            else:
                say("==> composed-tree validation skipped (single track)")

            if arguments.output:
                destination = arguments.output.resolve()
                if destination.exists():
                    shutil.rmtree(destination)
                shutil.copytree(composed, destination)
                say(f"    composed tree kept at {destination}")

            if not arguments.publish:
                say("DRY RUN -- nothing published (pass --publish)")
                return EXIT_OK

            say("==> publishing")
            commit = publish(
                composed, repo, parent, _commit_message(tracks),
                remote=arguments.remote, branch=arguments.branch, scratch=scratch,
            )
            say(f"    commit {commit[:7]} (parent {parent[:7]}) pushed to {arguments.branch}")
            say(f"    live shortly at {SITE_URL}/vaft/")
            return EXIT_OK
        finally:
            if arguments.keep_temp:
                say(f"    temporary tree kept at {scratch}")
            else:
                shutil.rmtree(scratch, ignore_errors=True)

    except PublishRace as race:
        print(f"ERROR: {race}", file=sys.stderr)
        return EXIT_RACE
    except ToolchainError as missing:
        print(f"ERROR: {missing}", file=sys.stderr)
        return EXIT_TOOLCHAIN
    except BuildError as failure:
        print(f"ERROR: {failure}", file=sys.stderr)
        print("Nothing was published.", file=sys.stderr)
        return EXIT_FAILED


if __name__ == "__main__":  # pragma: no cover - exercised through the CLI
    raise SystemExit(main())
